blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("posts/", views.post_list, name="post_list"),
    path("posts/search/", views.search, name="search"),
    path("posts/new/", views.post_new, name="post_new"),
    path(
        "posts/premium-user-guide/", views.premium_user_guide, name="premium_user_guide"
    ),
    path(
        "posts/premium/<str:slug>/",
        views.post_premium_detail,
        name="post_premium_detail",
    ),
    path("posts/<str:slug>/", views.post_detail, name="post_detail"),
    path("reviews/", views.review_list, name="review_list"),
    path("reviews/new/", views.review_new, name="review_new"),
    path("reviews/<int:pk>/", views.review_detail, name="review_detail"),
    path("reviews/<int:pk>/edit/", views.review_edit, name="review_edit"),
    path("demo/", views.demo_form, name="demo_form"),
    path("memogroup/<int:group_pk>/form/", views.momo_form, name="memo_form"),
    path("tags/", views.tag_list, name="tag_list"),
    path("tags/new/", views.tag_new, name="tag_new"),
    path("tags/<int:pk>/delete/", views.tag_delete, name="tag_delete"),
    path("tags/<int:pk>/edit/", views.tag_edit, name="tag_edit"),
    path("tags/<int:pk>/", views.tag_list_item, name="tag_list_item"),
    path("test/", views.test, name="test"),
]

mysite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from mysite import settings

urlpatterns = [
    path(settings.ADMIN_PREFIX, admin.site.urls),
    path(route="core/", view=include("core.urls")),
    path(route="cafe/", view=include("cafe.urls")),
    path("accounts/", include("accounts.urls")),
    path("hottrack/", include("hottrack.urls")),
    path("blog/", include("blog.urls")),
    path("shop/", include("shop.urls")),
    path("weblog/", include("weblog.urls")),
    path("", RedirectView.as_view(url="/hottrack/")),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/forms.py
from crispy_bootstrap5.bootstrap5 import FloatingField
from crispy_forms.bootstrap import PrependedText, TabHolder, Tab
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Row, Field
from django import forms
from django.core.validators import MinLengthValidator, MaxLengthValidator

from core.crispy_bootstrap5_ext.layout import BorderedTabHolder
from core.forms.widgets import HorizontalRadioSelect, StarRatingSelect
from .models import Review, Memo, Tag
from django.db import models


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["message", "rating"]
        # widgets = {"rating": forms.Select(choices=[(i, i) for i in range(1, 6)])}
        # widgets = {"rating": forms.RadioSelect(choices=[(i, i) for i in range(1, 6)])}
        # widgets = {
        #     "rating": HorizontalRadioSelect(choices=[(i, i) for i in range(1, 6)])
        # }

        widgets = {"rating": StarRatingSelect(choices=[(i, i) for i in range(1, 6)])}


class DemoForm(forms.Form):
    author = forms.CharField(label="작성자")
    instagram_username = forms.CharField(label="인스타그램 아이디")
    title = forms.CharField(label="제목")
    summary = forms.CharField(
        label="요약",
        help_text="본문에 대한 요약을 최소 20자, 최대 200자 내로 입력해주세요.",
        validators=[MinLengthValidator(20), MaxLengthValidator(200)],
    )
    content = forms.CharField(widget=forms.Textarea, label="내용")
    content_en = forms.CharField(widget=forms.Textarea, label="내용(영문)")

    field_order = [
        "title",
        "summary",
        "author",
        "instagram_username",
    ]  # 필드 순서 배치를 지원

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        # self.helper.form_action = ""
        # self.helper.form_tag = True
        # self.helper.disable_csrf = False
        # self.helper.form_class = "form-horizontal"
        # self.helper.label_class = "col-sm-2"
        # self.helper.field_class = "col-sm-10"
        self.helper.attrs = {"novalidate": True}
        self.helper.layout = Layout(
            FloatingField("title"),
            "summary",
            BorderedTabHolder(
                Tab("내용", "content"),
                Tab("내용 (영문)", "content_en"),
            ),
            Row(
                Field("author", autocomplete="off", wrapper_class="col-sm-6"),
                PrependedText("instagram_username", "@", wrapper_class="col-sm-6"),
            ),
        )
        self.helper.add_input(Submit("submit", "제출"))

    def clean(self):
        content = self.cleaned_data.get("content")
        summary = self.cleaned_data.get("summary")

        if content and not summary:
            raise forms.ValidationError("본문에 대한 요약을 입력해주세요.")


# class MemoForm(forms.Form):
#     class Status(models.TextChoices):
#         PRIVATE = "V", "비공개"
#         PUBLIC = "P", "공개"
#
#     message = forms.CharField(
#         max_length=140,
#         widget=forms.TextInput(attrs={"placeholder": "메모를 입력하세요"}),
#     )
#
#     status = forms.ChoiceField(initial=Status.PUBLIC, choices=Status.choices)


class MemoForm(forms.ModelForm):
    class Meta:
        model = Memo
        fields = ["message", "status"]


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ["name"]

blog/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required, permission_required
from django.core.files import File
from django.db.models import Q
from django.forms import formset_factory, modelformset_factory, inlineformset_factory
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.decorators.http import require_http_methods
from django_htmx.http import trigger_client_event
from vanilla import CreateView, ListView, DetailView, UpdateView, FormView

from blog.forms import ReviewForm, DemoForm, MemoForm, TagForm
from blog.models import Post, Review, Memo, MemoGroup, Tag
from core.decorators import login_required_hx


# Create your views here.


@login_required
@permission_required("blog.view_post", raise_exception=False)
def post_detail(request, slug):
    # slug 는 url 에만 사용할뿐, 조회에는 사용하지 않음
    post = get_object_or_404(Post, slug=slug)

    return HttpResponse(f"{post.pk} 번 글의 {post.slug}")


@login_required
@permission_required("blog.view_premium_post", login_url="blog:premium_user_guide")
def post_premium_detail(request, slug):
    return HttpResponse(f"프리미엄 컨텐츠 페이지 : {slug}")


def premium_user_guide(request):
    return HttpResponse("프리미엄 유저 가이드 페이지")


def post_list(request):
    query = request.GET.get("query", "").strip()
    post_qs = Post.objects.all()

    if query:
        post_qs = post_qs.filter(
            Q(tag_set__name__in=[query]) | Q(title__icontains=query)
        )

    post_qs = post_qs.select_related("author")
    post_qs = post_qs.prefetch_related("tag_set")
    return render(
        request, "blog/post_list.html", {"query": query, "post_list": post_qs}
    )


def search(request):
    query = request.GET.get("query", "").strip()
    return render(
        request,
        "blog/search.html",
        {
            "query": query,
        },
    )


def post_new(request):
    # 요청 데이터에서 값을 추출하고,
    # 입력값에 대한 유효성 검사를 필히 수행해야만 합니다.
    message: str = request.POST.get("message", "")
    photo: File = request.FILES.get("photo", "")
    errors = {
        "message": [],
        "photo": [],
    }

    # 요청 데이터에서 값을 추출하고,
    # 입력값에 대한 유효성 검사를 필히 수행해야만 합니다.
    # 장고에서는 이러한 유효성 검사를 Form이나 Serializer에 위임해서 처리합니다.
    if not message:
        errors["message"].append("message 필드는 필수 필드입니다.")
    if len(message) < 10:
        errors["message"].append("message 필드를 10글자 이상이어야 합니다.")
    if not photo:
        errors["photo"].append("photo 필드는 필수 필드입니다.")
    if photo and not photo.name.lower().endswith((".jpg", ".jpeg")):
        errors["photo"].append("jpg 파일만 업로드할 수 있습니다.")

    return render(
        request=request,
        template_name="blog/post_new.html",
        context={
            "message": message,
            "photo": photo,
            "errors": errors,
        },
    )


review_list = ListView.as_view(
    model=Review,
)

review_new = CreateView.as_view(model=Review, form_class=ReviewForm)

review_detail = DetailView.as_view(
    model=Review,
)

review_edit = UpdateView.as_view(
    model=Review,
    form_class=ReviewForm,
)

demo_form = FormView.as_view(form_class=DemoForm, template_name="blog/demo_form.html")


@login_required
def momo_form(request, group_pk):
    MemoFormSet = inlineformset_factory(
        parent_model=MemoGroup,
        # parent_model=get_user_model(),
        model=Memo,
        form=MemoForm,
        extra=3,
        can_delete=True,
    )

    memo_group = get_object_or_404(MemoGroup, pk=group_pk)

    queryset = None
    if request.method == "GET":
        formset = MemoFormSet(instance=memo_group, queryset=queryset)
    else:
        formset = MemoFormSet(
            data=request.POST,
            files=request.FILES,
            instance=memo_group,
            queryset=queryset,
        )
        if formset.is_valid():
            objs = formset.save()

            if objs:
                messages.success(request, f"메모 {len(objs)}개를 저장했습니다.")

            if formset.deleted_objects:
                messages.success(
                    request, f"메모 {len(formset.deleted_objects)}개를 삭제했습니다."
                )
            return redirect("blog:memo_form", group_pk)

    return render(
        request, "blog/momo_form.html", {"memo_group": memo_group, "formset": formset}
    )


# def tag_list(request):
#     tag_qs = Tag.objects.all()
#
#     query = request.GET.get("query", "")
#     if query:
#         tag_qs = tag_qs.filter(name__icontains=query)
#
#     # is_htmx = request.META.get("HTTP_HX_REQUEST") == "true"
#     if request.htmx:
#         template_name = "blog/_tag_list.html"
#     else:
#         template_name = "blog/tag_list.html"
#
#     return render(request, template_name, {"tag_list": tag_qs})


class TagListView(ListView):
    model = Tag
    queryset = Tag.objects.all()
    paginate_by = 10

    def get_queryset(self):
        qs = super().get_queryset()
        query = self.request.GET.get("query", "")
        if query:
            qs = qs.filter(name__icontains=query)
        return qs

    def get_template_names(self) -> list[str]:
        if self.request.htmx:
            template_name = "blog/_tag_list.html"
        else:
            template_name = "blog/tag_list.html"
        return [template_name]


tag_list = TagListView.as_view()


@login_required_hx
def tag_new(request, pk=None):
    if pk:
        instance = get_object_or_404(Tag, pk=pk)
    else:
        instance = None

    if request.method == "GET":
        form = TagForm(instance=instance)
    else:
        form = TagForm(data=request.POST, instance=instance)
        if form.is_valid():
            form.save()
            messages.success(request, "태그를 저장했습니다.")
            response = render(request, "core/_messages_as_event.html")
            response = trigger_client_event(response, "refresh-tag-list")
            return response

    return render(
        request,
        "blog/_tag_form.html",
        {
            "form": form,
        },
    )


def tag_edit(request, pk):
    return tag_new(request, pk)


def tag_list_item(request, pk):
    tag = get_object_or_404(Tag, pk=pk)
    return render(request, "blog/_tag_list_item.html", {"tag": tag})


@require_http_methods(["DELETE"])
def tag_delete(request, pk):
    tag = get_object_or_404(Tag, pk=pk)
    tag.delete()
    return HttpResponse("")


def test(request):
    return render(request, "blog/test.html")

blog/templates/blog/_tag_form.html
{# blog/templates/blog/_tag_form.html #}

{% load django_bootstrap5 partials %}

{% include "core/_messages_as_event.html" %}

{% partialdef tag-form %}
    <form hx-post="{{ request.get_full_path }}"
          hx-trigger="submit once"
          hx-swap="outerHTML"
          autocomplete="off"
          novalidate>
        {% csrf_token %}
        {% bootstrap_form form %}
    </form>
{% endpartialdef %}

{# "GET" 요청인 modal 요청. "POST" 요청은 modal 없이 폼 필드 응답만. #}
{% if request.method == "POST" %}
    {% partial tag-form %}
{% else %}
    {# https://getbootstrap.com/docs/5.3/components/modal/#examples #}
    <div class="modal fade" tabindex="-1">
        <div class="modal-dialog modal-dialog-scrollable">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">
                        {% if not form.instance.pk %}태그 생성{% else %}태그 수정{% endif %}
                    </h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                            aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {% partial tag-form %}
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">저장</button>
                    <button type="button" class="btn btn-warning" data-bs-dismiss="modal">취소</button>
                </div>
            </div>
        </div>
    </div>
    <script>
      (function () {
        const modalEl = document.currentScript.previousElementSibling;
        const modal = new bootstrap.Modal(modalEl);
        modal.show();

        {# 저장 버튼을 클릭하면, form submit 이벤트를 발생시킵니다. #}
        modalEl.querySelector("button[type=submit]").onclick = () => {
          const formEl = modalEl.querySelector("form");
          htmx.trigger(formEl, "submit");
        };

        {# refresh-tag-list 이벤트를 받으면 모달창을 닫습니다. #}
        document.body.addEventListener("refresh-tag-list", function () {
          modal.hide();
        });
      })();
    </script>
{% endif %}

blog/templates/blog/_tag_list.html
{% for tag in tag_list %}
    {% include "blog/_tag_list_item.html" %}
    {% if forloop.last %}
        {% if page_obj.has_next %}
        <div class="list-group-item list-group-item-action text-center"
             hx-get="{% url 'blog:tag_list' %}?page={{ page_obj.next_page_number }}"
             hx-trigger="revealed"
             hx-swap="outerHTML transition:true"
        >
        로딩 중...
        </div>
        {% else %}
            <div class="list-group-item list-group-item-action  text-center">
                페이지 끝 입니다.
            </div>
        {% endif %}
    {% endif %}
{% endfor %}

blog/templates/blog/_tag_list_item.html
{% load django_bootstrap5 %}

{% include 'core/_messages_as_event.html' %}

<div class="list-group-item d-flex justify-content-between align-items-center">
    <div
        style="cursor: pointer"
        hx-get="{% url 'blog:tag_edit' tag.pk %}"
        hx-trigger="click"
        hx-target="#modal-container"
        hx-swap="innerHTML"
    >
        {{ tag.name }}
    </div>
    <span
            class="text-danger"
            style="cursor: pointer"
            hx-trigger="click"
            hx-confirm="{{ tag.name }} 태그를 삭제하시겠습니까?"
            hx-delete="{% url 'blog:tag_delete' tag.pk %}"
            hx-target="closest .list-group-item"
            hx-swap="delete"
    >
        X
    </span>
    </div>

blog/templates/blog/base.html
{# blog/templates/blog/base.html #}
{% load django_bootstrap5 static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8" />
    <title>{% block title %}{% endblock %}</title>
    {% bootstrap_css %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/htmx/1.9.10/htmx.min.js"></script>
</head>
<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
    <main style="width: 400px; margin: 1em;">
        <h1>유저 : {{ request.user }}</h1>
        {% block content %}{% endblock %}
    </main>
    <div id="modal-container"></div>
    <script>
        document.body.addEventListener('htmx:configRequest', function (event) {
          const htmxElement = event.detail.elt;
          const isGetRequest = htmxElement.hasAttribute('hx-get');
          if ( isGetRequest && htmxElement.hasAttribute('hx-get-with-timestamp') ) {
            const paramName = htmxElement.getAttribute('hx-get-with-timestamp') || '_';
            event.detail.parameters[paramName] = new Date().getTime();
          }
        });
    </script>
    {% bootstrap_javascript %}
    <script src="{% static 'core/toast-messages.js' %}"></script>
    {% include "core/_messages_as_event.html" %}
    {% block extra-script %}{% endblock %}
</body>
</html>

blog/templates/blog/demo_form.html
{% load crispy_forms_tags %}

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
<div class="container my-3">
    {% crispy form form.helper %}
</div>

blog/templates/blog/demo_form_field.html
{% load widget_tweaks %}

<div class="my-2">
    {{ form_field|add_label_class:"form-label"}}<br/>
    {{ form_field|add_class:"form-control" }}
    <div class="form-text text-success">{{ form_field.help_text }}</div>
    <div class="form-text text-danger">
        {% for error in form_field.errors %}
            {{ error }}<br>
        {% endfor %}
    </div>
</div>

blog/templates/blog/post_list.html
{# blog/templates/blog/post_list.html #}

<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>블로그</title>

    {# Minimal CSS Framework #}
    {# https://picocss.com/docs/ or https://andybrewer.github.io/mvp/ #}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@1/css/pico.min.css">

</head>
<body>

<main class="container">
    <section>
        <h2>블로그 포스팅</h2>

        <form action="" method="get">
            <input type="text" name="query" value="{{ query }}"
                   placeholder="검색어를 입력해주세요."/>
            <input type="submit" value="검색"/>
        </form>

        <form action="/blog/new/" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="text" name="message"
                   placeholder="메시지를 입력해주세요.">
            <input type="file" name="photo" placeholder="사진"/>
            <input type="submit" value="저장하기"/>
        </form>

        <table>
            {% for post in post_list %}
                <tr>
                    <td>{{ post.title }}</td>
                    <td>{{ post.author.username }}</td>
                    <td>
                        {% for tag in post.tag_set.all %}
                            <mark>{{ tag.name }}</mark>
                        {% endfor %}
                    </td>
                </tr>
            {% endfor %}
        </table>
    </section>
</main>

</body>
</html>

blog/templates/blog/post_new.html
{{ errors }}

<hr/>
request.GET: {{ request.GET }}<br/>
request.POST: {{ request.POST }}<br/>
request.FILES: {{ request.FILES }}<br/>

blog/templates/blog/review_detail.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h2>{{ review }}</h2>
    <hr>
    <a href="{% url 'blog:review_list' %}">List</a>
    <a href="{% url 'blog:review_edit' review.pk %}">Edit</a>
</body>
</html>

blog/templates/blog/review_form.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Review Form</title>
</head>
<body>
<h2>Review Form</h2>
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit">
</form>
</body>
</html>

blog/templates/blog/search.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>검색결과</title>
</head>
<body>
{% if not query %}
    <p>입력된 검색어가 없습니다.</p>
{% else %}
    <p>검색어는 "{{ query }}" 입니다.</p>
{% endif %}

<hr/>
request.GET: {{ request.GET }}<br/>
request.POST: {{ request.POST }}<br/>
request.FILES: {{ request.FILES }}<br/>
</body>
</html>

blog/templates/blog/tag_form.html
{% extends "blog/base.html" %}
{% block title %}태그 폼{% endblock %}
{% block content %}
    <h2>태그 폼</h2>
    {% include "blog/_tag_form.html" %}
{% endblock %}

blog/templates/blog/tag_list.html
{% extends "blog/base.html" %}
{% load django_bootstrap5 %}
{% block title %}태그 목록{% endblock %}
{% block content %}
    <h2>태그 목록</h2>

    <button class="btn btn-primary"
            hx-get="{% url 'blog:tag_new' %}"
            hx-get-with-timestamp
            hx-trigger="click"
            hx-target="#modal-container"
            hx-swap="innerHTML"
    >
    새 태그
    </button>

    <button class="btn btn-primary my-3"
            hx-get="{% url 'blog:tag_list' %}?page={{ request.GET.page|default:1 }}"
            hx-get-with-timestamp
            hx-target="#tag-list-container .list-group"
            hx-trigger="click, refresh-tag-list from:body"
            hx-swap="innerHTML transition:true"
    >
    새로고침
    </button>
    <div class="position-relative">
    <input type="text" name="query" class="form-control my-3"
           hx-get="{% url 'blog:tag_list' %}"
           hx-get-with-timestamp
           hx-trigger="keyup[target.value.length === 0 || target.value.length >= 2] changed delay:400ms"
           hx-target="#tag-list-container .list-group"
           hx-swap="innerHTML transition:true"
           hx-indicator="#tag-list-query-indicator"
    />

    {# indicator가 사용될 때에는 .htmx-request가 적용됩니다. #}
    <div id="tag-list-query-indicator" class="htmx-indicator">
        {# ref: https://getbootstrap.com/docs/5.3/components/spinners/#growing-spinner #}
        <div class="spinner-grow text-primary" style="width: 20px; height: 20px; position: absolute; top: 50%; margin-top: -10px; right: 10px;">
        </div>
    </div>
</div>

    <div id="tag-list-container">
        <div class="list-group">
            {% include "blog/_tag_list.html" %}
        </div>
    </div>

    <hr />
    <a href="{% url 'blog:tag_new' %}">새 태그</a>
{% endblock %}

blog/templates/blog/test.html
<!doctype html>
<html lang="ko">
<head>
<meta charset="UTF-8"/>
<title>htmx</title>
    <script src="https://unpkg.com/htmx.org@1.9.10/dist/htmx.min.js"></script>
</head>
<body>

<div>
{% include 'components-pure/hello-world.html' with name="파이썬" %}

{% with name="장고" %}
    {% include 'components-pure/hello-world.html' %}
{% endwith %}
{% include 'components-pure/hello-world.html' %}
</div>

<button
    hx-get="{% url 'blog:tag_list' %}"
    hx-trigger="click"
    hx-target="#tag-list-container"
    hx-swap="innerHTML transition:true"
>
    새로고침
</button>
<div id="tag-list-container"></div>


</body>
</html>